Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Ambil data dari MySQL
mysql_query = "SELECT * FROM iris_data"
mysql_df = pd.read_sql(mysql_query, mysql_engine)

# Ambil data dari PostgreSQL
pg_query = "SELECT * FROM postgresql"
pg_df = pd.read_sql(pg_query, postgres_engine)

print(mysql_df)
print()
print(pg_df)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mgaierror[0m                                  Traceback (most recent call last)
File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/pymysql/connections.py:649[0m, in [0;36mConnection.connect[0;34m(self, sock)[0m
[1;32m    648[0m [38;5;28;01mtry[39;00m:
[0;32m--> 649[0m     sock [38;5;241m=[39m [43msocket[49m[38;5;241;43m.[39;49m[43mcreate_connection[49m[43m([49m
[1;32m    650[0m [43m        [49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mhost[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mport[49m[43m)[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect_timeout[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m
[1;32m    651[0m [43m    [49m[43m)[49m
[1;32m    652[0m     [38;5;28;01mbreak[39;00m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/socket.py:828[0m, in [0;36mcreate_connection[0;34m(address, timeout, source_address, all_errors)[0m
[1;32m    827[0m exceptions [38;5;241m=[39m []
[0;32m--> 828[0m [38;5;28;01mfor[39;00m res [38;5;129;01min[39;00m [43mgetaddrinfo[49m[43m([49m[43mhost[49m[43m,[49m[43m [49m[43mport[49m[43m,[49m[43m [49m[38;5;241;43m0[39;49m[43m,[49m[43m [49m[43mSOCK_STREAM[49m[43m)[49m:
[1;32m    829[0m     af, socktype, proto, canonname, sa [38;5;241m=[39m res

File [0;32m/usr/local/python/3.12.1/lib/python3.12/socket.py:963[0m, in [0;36mgetaddrinfo[0;34m(host, port, family, type, proto, flags)[0m
[1;32m    962[0m addrlist [38;5;241m=[39m []
[0;32m--> 963[0m [38;5;28;01mfor[39;00m res [38;5;129;01min[39;00m [43m_socket[49m[38;5;241;43m.[39;49m[43mgetaddrinfo[49m[43m([49m[43mhost[49m[43m,[49m[43m [49m[43mport[49m[43m,[49m[43m [49m[43mfamily[49m[43m,[49m[43m [49m[38;5;28;43mtype[39;49m[43m,[49m[43m [49m[43mproto[49m[43m,[49m[43m [49m[43mflags[49m[43m)[49m:
[1;32m    964[0m     af, socktype, proto, canonname, sa [38;5;241m=[39m res

[0;31mgaierror[0m: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

[0;31mOperationalError[0m                          Traceback (most recent call last)
File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/base.py:146[0m, in [0;36mConnection.__init__[0;34m(self, engine, connection, _has_events, _allow_revalidate, _allow_autobegin)[0m
[1;32m    145[0m [38;5;28;01mtry[39;00m:
[0;32m--> 146[0m     [38;5;28mself[39m[38;5;241m.[39m_dbapi_connection [38;5;241m=[39m [43mengine[49m[38;5;241;43m.[39;49m[43mraw_connection[49m[43m([49m[43m)[49m
[1;32m    147[0m [38;5;28;01mexcept[39;00m dialect[38;5;241m.[39mloaded_dbapi[38;5;241m.[39mError [38;5;28;01mas[39;00m err:

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/base.py:3298[0m, in [0;36mEngine.raw_connection[0;34m(self)[0m
[1;32m   3277[0m [38;5;250m[39m[38;5;124;03m"""Return a "raw" DBAPI connection from the connection pool.[39;00m
[1;32m   3278[0m 
[1;32m   3279[0m [38;5;124;03mThe returned object is a proxied version of the DBAPI[39;00m
[0;32m   (...)[0m
[1;32m   3296[0m 
[1;32m   3297[0m [38;5;124;03m"""[39;00m
[0;32m-> 3298[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mpool[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/base.py:449[0m, in [0;36mPool.connect[0;34m(self)[0m
[1;32m    442[0m [38;5;250m[39m[38;5;124;03m"""Return a DBAPI connection from the pool.[39;00m
[1;32m    443[0m 
[1;32m    444[0m [38;5;124;03mThe connection is instrumented such that when its[39;00m
[0;32m   (...)[0m
[1;32m    447[0m 
[1;32m    448[0m [38;5;124;03m"""[39;00m
[0;32m--> 449[0m [38;5;28;01mreturn[39;00m [43m_ConnectionFairy[49m[38;5;241;43m.[39;49m[43m_checkout[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/base.py:1264[0m, in [0;36m_ConnectionFairy._checkout[0;34m(cls, pool, threadconns, fairy)[0m
[1;32m   1263[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m fairy:
[0;32m-> 1264[0m     fairy [38;5;241m=[39m [43m_ConnectionRecord[49m[38;5;241;43m.[39;49m[43mcheckout[49m[43m([49m[43mpool[49m[43m)[49m
[1;32m   1266[0m     [38;5;28;01mif[39;00m threadconns [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/base.py:713[0m, in [0;36m_ConnectionRecord.checkout[0;34m(cls, pool)[0m
[1;32m    712[0m [38;5;28;01melse[39;00m:
[0;32m--> 713[0m     rec [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_do_get[49m[43m([49m[43m)[49m
[1;32m    715[0m [38;5;28;01mtry[39;00m:

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/impl.py:179[0m, in [0;36mQueuePool._do_get[0;34m(self)[0m
[1;32m    178[0m [38;5;28;01mexcept[39;00m:
[0;32m--> 179[0m [43m    [49m[38;5;28;43;01mwith[39;49;00m[43m [49m[43mutil[49m[38;5;241;43m.[39;49m[43msafe_reraise[49m[43m([49m[43m)[49m[43m:[49m
[1;32m    180[0m [43m        [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_dec_overflow[49m[43m([49m[43m)[49m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py:146[0m, in [0;36msafe_reraise.__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m    145[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[0;32m--> 146[0m     [38;5;28;01mraise[39;00m exc_value[38;5;241m.[39mwith_traceback(exc_tb)
[1;32m    147[0m [38;5;28;01melse[39;00m:

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/impl.py:177[0m, in [0;36mQueuePool._do_get[0;34m(self)[0m
[1;32m    176[0m [38;5;28;01mtry[39;00m:
[0;32m--> 177[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_create_connection[49m[43m([49m[43m)[49m
[1;32m    178[0m [38;5;28;01mexcept[39;00m:

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/base.py:390[0m, in [0;36mPool._create_connection[0;34m(self)[0m
[1;32m    388[0m [38;5;250m[39m[38;5;124;03m"""Called by subclasses to create a new ConnectionRecord."""[39;00m
[0;32m--> 390[0m [38;5;28;01mreturn[39;00m [43m_ConnectionRecord[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/base.py:675[0m, in [0;36m_ConnectionRecord.__init__[0;34m(self, pool, connect)[0m
[1;32m    674[0m [38;5;28;01mif[39;00m connect:
[0;32m--> 675[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__connect[49m[43m([49m[43m)[49m
[1;32m    676[0m [38;5;28mself[39m[38;5;241m.[39mfinalize_callback [38;5;241m=[39m deque()

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/base.py:901[0m, in [0;36m_ConnectionRecord.__connect[0;34m(self)[0m
[1;32m    900[0m [38;5;28;01mexcept[39;00m [38;5;167;01mBaseException[39;00m [38;5;28;01mas[39;00m e:
[0;32m--> 901[0m [43m    [49m[38;5;28;43;01mwith[39;49;00m[43m [49m[43mutil[49m[38;5;241;43m.[39;49m[43msafe_reraise[49m[43m([49m[43m)[49m[43m:[49m
[1;32m    902[0m [43m        [49m[43mpool[49m[38;5;241;43m.[39;49m[43mlogger[49m[38;5;241;43m.[39;49m[43mdebug[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mError on connect(): [39;49m[38;5;132;43;01m%s[39;49;00m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43me[49m[43m)[49m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py:146[0m, in [0;36msafe_reraise.__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m    145[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[0;32m--> 146[0m     [38;5;28;01mraise[39;00m exc_value[38;5;241m.[39mwith_traceback(exc_tb)
[1;32m    147[0m [38;5;28;01melse[39;00m:

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/base.py:897[0m, in [0;36m_ConnectionRecord.__connect[0;34m(self)[0m
[1;32m    896[0m [38;5;28mself[39m[38;5;241m.[39mstarttime [38;5;241m=[39m time[38;5;241m.[39mtime()
[0;32m--> 897[0m [38;5;28mself[39m[38;5;241m.[39mdbapi_connection [38;5;241m=[39m connection [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_invoke_creator[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m
[1;32m    898[0m pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mCreated new connection [39m[38;5;132;01m%r[39;00m[38;5;124m"[39m, connection)

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/create.py:646[0m, in [0;36mcreate_engine.<locals>.connect[0;34m(connection_record)[0m
[1;32m    644[0m             [38;5;28;01mreturn[39;00m connection
[0;32m--> 646[0m [38;5;28;01mreturn[39;00m [43mdialect[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[43mcargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcparams[49m[43m)[49m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/default.py:622[0m, in [0;36mDefaultDialect.connect[0;34m(self, *cargs, **cparams)[0m
[1;32m    620[0m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m([38;5;28mself[39m, [38;5;241m*[39mcargs, [38;5;241m*[39m[38;5;241m*[39mcparams):
[1;32m    621[0m     [38;5;66;03m# inherits the docstring from interfaces.Dialect.connect[39;00m
[0;32m--> 622[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mloaded_dbapi[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[43mcargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcparams[49m[43m)[49m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/pymysql/connections.py:361[0m, in [0;36mConnection.__init__[0;34m(self, user, password, host, database, unix_socket, port, charset, collation, sql_mode, read_default_file, conv, use_unicode, client_flag, cursorclass, init_command, connect_timeout, read_default_group, autocommit, local_infile, max_allowed_packet, defer_connect, auth_plugin_map, read_timeout, write_timeout, bind_address, binary_prefix, program_name, server_public_key, ssl, ssl_ca, ssl_cert, ssl_disabled, ssl_key, ssl_key_password, ssl_verify_cert, ssl_verify_identity, compress, named_pipe, passwd, db)[0m
[1;32m    360[0m [38;5;28;01melse[39;00m:
[0;32m--> 361[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/pymysql/connections.py:716[0m, in [0;36mConnection.connect[0;34m(self, sock)[0m
[1;32m    715[0m         [38;5;28mprint[39m(exc[38;5;241m.[39mtraceback)
[0;32m--> 716[0m     [38;5;28;01mraise[39;00m exc
[1;32m    718[0m [38;5;66;03m# If e is neither DatabaseError or IOError, It's a bug.[39;00m
[1;32m    719[0m [38;5;66;03m# But raising AssertionError hides original error.[39;00m
[1;32m    720[0m [38;5;66;03m# So just reraise it.[39;00m

[0;31mOperationalError[0m: (2003, "Can't connect to MySQL server on 'mysql-b2a9b82-iris-mysql.g.aivencloud.com' ([Errno -2] Name or service not known)")

The above exception was the direct cause of the following exception:

[0;31mOperationalError[0m                          Traceback (most recent call last)
Cell [0;32mIn[8], line 3[0m
[1;32m      1[0m [38;5;66;03m# Ambil data dari MySQL[39;00m
[1;32m      2[0m mysql_query [38;5;241m=[39m [38;5;124m"[39m[38;5;124mSELECT * FROM iris_data[39m[38;5;124m"[39m
[0;32m----> 3[0m mysql_df [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mread_sql[49m[43m([49m[43mmysql_query[49m[43m,[49m[43m [49m[43mmysql_engine[49m[43m)[49m
[1;32m      5[0m [38;5;66;03m# Ambil data dari PostgreSQL[39;00m
[1;32m      6[0m pg_query [38;5;241m=[39m [38;5;124m"[39m[38;5;124mSELECT * FROM postgresql[39m[38;5;124m"[39m

File [0;32m~/.local/lib/python3.12/site-packages/pandas/io/sql.py:704[0m, in [0;36mread_sql[0;34m(sql, con, index_col, coerce_float, params, parse_dates, columns, chunksize, dtype_backend, dtype)[0m
[1;32m    701[0m     dtype_backend [38;5;241m=[39m [38;5;124m"[39m[38;5;124mnumpy[39m[38;5;124m"[39m  [38;5;66;03m# type: ignore[assignment][39;00m
[1;32m    702[0m [38;5;28;01massert[39;00m dtype_backend [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m lib[38;5;241m.[39mno_default
[0;32m--> 704[0m [38;5;28;01mwith[39;00m [43mpandasSQL_builder[49m[43m([49m[43mcon[49m[43m)[49m [38;5;28;01mas[39;00m pandas_sql:
[1;32m    705[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(pandas_sql, SQLiteDatabase):
[1;32m    706[0m         [38;5;28;01mreturn[39;00m pandas_sql[38;5;241m.[39mread_query(
[1;32m    707[0m             sql,
[1;32m    708[0m             index_col[38;5;241m=[39mindex_col,
[0;32m   (...)[0m
[1;32m    714[0m             dtype[38;5;241m=[39mdtype,
[1;32m    715[0m         )

File [0;32m~/.local/lib/python3.12/site-packages/pandas/io/sql.py:906[0m, in [0;36mpandasSQL_builder[0;34m(con, schema, need_transaction)[0m
[1;32m    903[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m([38;5;124m"[39m[38;5;124mUsing URI string without sqlalchemy installed.[39m[38;5;124m"[39m)
[1;32m    905[0m [38;5;28;01mif[39;00m sqlalchemy [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m [38;5;28misinstance[39m(con, ([38;5;28mstr[39m, sqlalchemy[38;5;241m.[39mengine[38;5;241m.[39mConnectable)):
[0;32m--> 906[0m     [38;5;28;01mreturn[39;00m [43mSQLDatabase[49m[43m([49m[43mcon[49m[43m,[49m[43m [49m[43mschema[49m[43m,[49m[43m [49m[43mneed_transaction[49m[43m)[49m
[1;32m    908[0m adbc [38;5;241m=[39m import_optional_dependency([38;5;124m"[39m[38;5;124madbc_driver_manager.dbapi[39m[38;5;124m"[39m, errors[38;5;241m=[39m[38;5;124m"[39m[38;5;124mignore[39m[38;5;124m"[39m)
[1;32m    909[0m [38;5;28;01mif[39;00m adbc [38;5;129;01mand[39;00m [38;5;28misinstance[39m(con, adbc[38;5;241m.[39mConnection):

File [0;32m~/.local/lib/python3.12/site-packages/pandas/io/sql.py:1636[0m, in [0;36mSQLDatabase.__init__[0;34m(self, con, schema, need_transaction)[0m
[1;32m   1634[0m     [38;5;28mself[39m[38;5;241m.[39mexit_stack[38;5;241m.[39mcallback(con[38;5;241m.[39mdispose)
[1;32m   1635[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(con, Engine):
[0;32m-> 1636[0m     con [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mexit_stack[38;5;241m.[39menter_context([43mcon[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m)
[1;32m   1637[0m [38;5;28;01mif[39;00m need_transaction [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m con[38;5;241m.[39min_transaction():
[1;32m   1638[0m     [38;5;28mself[39m[38;5;241m.[39mexit_stack[38;5;241m.[39menter_context(con[38;5;241m.[39mbegin())

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/base.py:3274[0m, in [0;36mEngine.connect[0;34m(self)[0m
[1;32m   3251[0m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m Connection:
[1;32m   3252[0m [38;5;250m    [39m[38;5;124;03m"""Return a new :class:`_engine.Connection` object.[39;00m
[1;32m   3253[0m 
[1;32m   3254[0m [38;5;124;03m    The :class:`_engine.Connection` acts as a Python context manager, so[39;00m
[0;32m   (...)[0m
[1;32m   3271[0m 
[1;32m   3272[0m [38;5;124;03m    """[39;00m
[0;32m-> 3274[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_connection_cls[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/base.py:148[0m, in [0;36mConnection.__init__[0;34m(self, engine, connection, _has_events, _allow_revalidate, _allow_autobegin)[0m
[1;32m    146[0m         [38;5;28mself[39m[38;5;241m.[39m_dbapi_connection [38;5;241m=[39m engine[38;5;241m.[39mraw_connection()
[1;32m    147[0m     [38;5;28;01mexcept[39;00m dialect[38;5;241m.[39mloaded_dbapi[38;5;241m.[39mError [38;5;28;01mas[39;00m err:
[0;32m--> 148[0m         [43mConnection[49m[38;5;241;43m.[39;49m[43m_handle_dbapi_exception_noconnection[49m[43m([49m
[1;32m    149[0m [43m            [49m[43merr[49m[43m,[49m[43m [49m[43mdialect[49m[43m,[49m[43m [49m[43mengine[49m
[1;32m    150[0m [43m        [49m[43m)[49m
[1;32m    151[0m         [38;5;28;01mraise[39;00m
[1;32m    152[0m [38;5;28;01melse[39;00m:

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/base.py:2439[0m, in [0;36mConnection._handle_dbapi_exception_noconnection[0;34m(cls, e, dialect, engine, is_disconnect, invalidate_pool_on_disconnect, is_pre_ping)[0m
[1;32m   2437[0m [38;5;28;01melif[39;00m should_wrap:
[1;32m   2438[0m     [38;5;28;01massert[39;00m sqlalchemy_exception [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[0;32m-> 2439[0m     [38;5;28;01mraise[39;00m sqlalchemy_exception[38;5;241m.[39mwith_traceback(exc_info[[38;5;241m2[39m]) [38;5;28;01mfrom[39;00m [38;5;21;01me[39;00m
[1;32m   2440[0m [38;5;28;01melse[39;00m:
[1;32m   2441[0m     [38;5;28;01massert[39;00m exc_info[[38;5;241m1[39m] [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/base.py:146[0m, in [0;36mConnection.__init__[0;34m(self, engine, connection, _has_events, _allow_revalidate, _allow_autobegin)[0m
[1;32m    144[0m [38;5;28;01mif[39;00m connection [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    145[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 146[0m         [38;5;28mself[39m[38;5;241m.[39m_dbapi_connection [38;5;241m=[39m [43mengine[49m[38;5;241;43m.[39;49m[43mraw_connection[49m[43m([49m[43m)[49m
[1;32m    147[0m     [38;5;28;01mexcept[39;00m dialect[38;5;241m.[39mloaded_dbapi[38;5;241m.[39mError [38;5;28;01mas[39;00m err:
[1;32m    148[0m         Connection[38;5;241m.[39m_handle_dbapi_exception_noconnection(
[1;32m    149[0m             err, dialect, engine
[1;32m    150[0m         )

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/base.py:3298[0m, in [0;36mEngine.raw_connection[0;34m(self)[0m
[1;32m   3276[0m [38;5;28;01mdef[39;00m [38;5;21mraw_connection[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m PoolProxiedConnection:
[1;32m   3277[0m [38;5;250m    [39m[38;5;124;03m"""Return a "raw" DBAPI connection from the connection pool.[39;00m
[1;32m   3278[0m 
[1;32m   3279[0m [38;5;124;03m    The returned object is a proxied version of the DBAPI[39;00m
[0;32m   (...)[0m
[1;32m   3296[0m 
[1;32m   3297[0m [38;5;124;03m    """[39;00m
[0;32m-> 3298[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mpool[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/base.py:449[0m, in [0;36mPool.connect[0;34m(self)[0m
[1;32m    441[0m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m PoolProxiedConnection:
[1;32m    442[0m [38;5;250m    [39m[38;5;124;03m"""Return a DBAPI connection from the pool.[39;00m
[1;32m    443[0m 
[1;32m    444[0m [38;5;124;03m    The connection is instrumented such that when its[39;00m
[0;32m   (...)[0m
[1;32m    447[0m 
[1;32m    448[0m [38;5;124;03m    """[39;00m
[0;32m--> 449[0m     [38;5;28;01mreturn[39;00m [43m_ConnectionFairy[49m[38;5;241;43m.[39;49m[43m_checkout[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/base.py:1264[0m, in [0;36m_ConnectionFairy._checkout[0;34m(cls, pool, threadconns, fairy)[0m
[1;32m   1256[0m [38;5;129m@classmethod[39m
[1;32m   1257[0m [38;5;28;01mdef[39;00m [38;5;21m_checkout[39m(
[1;32m   1258[0m     [38;5;28mcls[39m,
[0;32m   (...)[0m
[1;32m   1261[0m     fairy: Optional[_ConnectionFairy] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m   1262[0m ) [38;5;241m-[39m[38;5;241m>[39m _ConnectionFairy:
[1;32m   1263[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m fairy:
[0;32m-> 1264[0m         fairy [38;5;241m=[39m [43m_ConnectionRecord[49m[38;5;241;43m.[39;49m[43mcheckout[49m[43m([49m[43mpool[49m[43m)[49m
[1;32m   1266[0m         [38;5;28;01mif[39;00m threadconns [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m   1267[0m             threadconns[38;5;241m.[39mcurrent [38;5;241m=[39m weakref[38;5;241m.[39mref(fairy)

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/base.py:713[0m, in [0;36m_ConnectionRecord.checkout[0;34m(cls, pool)[0m
[1;32m    711[0m     rec [38;5;241m=[39m cast(_ConnectionRecord, pool[38;5;241m.[39m_do_get())
[1;32m    712[0m [38;5;28;01melse[39;00m:
[0;32m--> 713[0m     rec [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_do_get[49m[43m([49m[43m)[49m
[1;32m    715[0m [38;5;28;01mtry[39;00m:
[1;32m    716[0m     dbapi_connection [38;5;241m=[39m rec[38;5;241m.[39mget_connection()

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/impl.py:179[0m, in [0;36mQueuePool._do_get[0;34m(self)[0m
[1;32m    177[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_create_connection()
[1;32m    178[0m [38;5;28;01mexcept[39;00m:
[0;32m--> 179[0m [43m    [49m[38;5;28;43;01mwith[39;49;00m[43m [49m[43mutil[49m[38;5;241;43m.[39;49m[43msafe_reraise[49m[43m([49m[43m)[49m[43m:[49m
[1;32m    180[0m [43m        [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_dec_overflow[49m[43m([49m[43m)[49m
[1;32m    181[0m     [38;5;28;01mraise[39;00m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py:146[0m, in [0;36msafe_reraise.__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m    144[0m     [38;5;28;01massert[39;00m exc_value [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[1;32m    145[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[0;32m--> 146[0m     [38;5;28;01mraise[39;00m exc_value[38;5;241m.[39mwith_traceback(exc_tb)
[1;32m    147[0m [38;5;28;01melse[39;00m:
[1;32m    148[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/impl.py:177[0m, in [0;36mQueuePool._do_get[0;34m(self)[0m
[1;32m    175[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_inc_overflow():
[1;32m    176[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 177[0m         [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_create_connection[49m[43m([49m[43m)[49m
[1;32m    178[0m     [38;5;28;01mexcept[39;00m:
[1;32m    179[0m         [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/base.py:390[0m, in [0;36mPool._create_connection[0;34m(self)[0m
[1;32m    387[0m [38;5;28;01mdef[39;00m [38;5;21m_create_connection[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m ConnectionPoolEntry:
[1;32m    388[0m [38;5;250m    [39m[38;5;124;03m"""Called by subclasses to create a new ConnectionRecord."""[39;00m
[0;32m--> 390[0m     [38;5;28;01mreturn[39;00m [43m_ConnectionRecord[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/base.py:675[0m, in [0;36m_ConnectionRecord.__init__[0;34m(self, pool, connect)[0m
[1;32m    673[0m [38;5;28mself[39m[38;5;241m.[39m__pool [38;5;241m=[39m pool
[1;32m    674[0m [38;5;28;01mif[39;00m connect:
[0;32m--> 675[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__connect[49m[43m([49m[43m)[49m
[1;32m    676[0m [38;5;28mself[39m[38;5;241m.[39mfinalize_callback [38;5;241m=[39m deque()

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/base.py:901[0m, in [0;36m_ConnectionRecord.__connect[0;34m(self)[0m
[1;32m    899[0m     [38;5;28mself[39m[38;5;241m.[39mfresh [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m    900[0m [38;5;28;01mexcept[39;00m [38;5;167;01mBaseException[39;00m [38;5;28;01mas[39;00m e:
[0;32m--> 901[0m [43m    [49m[38;5;28;43;01mwith[39;49;00m[43m [49m[43mutil[49m[38;5;241;43m.[39;49m[43msafe_reraise[49m[43m([49m[43m)[49m[43m:[49m
[1;32m    902[0m [43m        [49m[43mpool[49m[38;5;241;43m.[39;49m[43mlogger[49m[38;5;241;43m.[39;49m[43mdebug[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mError on connect(): [39;49m[38;5;132;43;01m%s[39;49;00m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43me[49m[43m)[49m
[1;32m    903[0m [38;5;28;01melse[39;00m:
[1;32m    904[0m     [38;5;66;03m# in SQLAlchemy 1.4 the first_connect event is not used by[39;00m
[1;32m    905[0m     [38;5;66;03m# the engine, so this will usually not be set[39;00m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py:146[0m, in [0;36msafe_reraise.__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m    144[0m     [38;5;28;01massert[39;00m exc_value [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[1;32m    145[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[0;32m--> 146[0m     [38;5;28;01mraise[39;00m exc_value[38;5;241m.[39mwith_traceback(exc_tb)
[1;32m    147[0m [38;5;28;01melse[39;00m:
[1;32m    148[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/pool/base.py:897[0m, in [0;36m_ConnectionRecord.__connect[0;34m(self)[0m
[1;32m    895[0m [38;5;28;01mtry[39;00m:
[1;32m    896[0m     [38;5;28mself[39m[38;5;241m.[39mstarttime [38;5;241m=[39m time[38;5;241m.[39mtime()
[0;32m--> 897[0m     [38;5;28mself[39m[38;5;241m.[39mdbapi_connection [38;5;241m=[39m connection [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_invoke_creator[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m
[1;32m    898[0m     pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mCreated new connection [39m[38;5;132;01m%r[39;00m[38;5;124m"[39m, connection)
[1;32m    899[0m     [38;5;28mself[39m[38;5;241m.[39mfresh [38;5;241m=[39m [38;5;28;01mTrue[39;00m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/create.py:646[0m, in [0;36mcreate_engine.<locals>.connect[0;34m(connection_record)[0m
[1;32m    643[0m         [38;5;28;01mif[39;00m connection [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    644[0m             [38;5;28;01mreturn[39;00m connection
[0;32m--> 646[0m [38;5;28;01mreturn[39;00m [43mdialect[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[43mcargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcparams[49m[43m)[49m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/sqlalchemy/engine/default.py:622[0m, in [0;36mDefaultDialect.connect[0;34m(self, *cargs, **cparams)[0m
[1;32m    620[0m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m([38;5;28mself[39m, [38;5;241m*[39mcargs, [38;5;241m*[39m[38;5;241m*[39mcparams):
[1;32m    621[0m     [38;5;66;03m# inherits the docstring from interfaces.Dialect.connect[39;00m
[0;32m--> 622[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mloaded_dbapi[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[43mcargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcparams[49m[43m)[49m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/pymysql/connections.py:361[0m, in [0;36mConnection.__init__[0;34m(self, user, password, host, database, unix_socket, port, charset, collation, sql_mode, read_default_file, conv, use_unicode, client_flag, cursorclass, init_command, connect_timeout, read_default_group, autocommit, local_infile, max_allowed_packet, defer_connect, auth_plugin_map, read_timeout, write_timeout, bind_address, binary_prefix, program_name, server_public_key, ssl, ssl_ca, ssl_cert, ssl_disabled, ssl_key, ssl_key_password, ssl_verify_cert, ssl_verify_identity, compress, named_pipe, passwd, db)[0m
[1;32m    359[0m     [38;5;28mself[39m[38;5;241m.[39m_sock [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m    360[0m [38;5;28;01melse[39;00m:
[0;32m--> 361[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/pymysql/connections.py:716[0m, in [0;36mConnection.connect[0;34m(self, sock)[0m
[1;32m    714[0m     [38;5;28;01mif[39;00m DEBUG:
[1;32m    715[0m         [38;5;28mprint[39m(exc[38;5;241m.[39mtraceback)
[0;32m--> 716[0m     [38;5;28;01mraise[39;00m exc
[1;32m    718[0m [38;5;66;03m# If e is neither DatabaseError or IOError, It's a bug.[39;00m
[1;32m    719[0m [38;5;66;03m# But raising AssertionError hides original error.[39;00m
[1;32m    720[0m [38;5;66;03m# So just reraise it.[39;00m
[1;32m    721[0m [38;5;28;01mraise[39;00m

[0;31mOperationalError[0m: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'mysql-b2a9b82-iris-mysql.g.aivencloud.com' ([Errno -2] Name or service not known)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

